# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 03:08
from __future__ import unicode_literals

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('change_type', models.CharField(blank=True, choices=[('available', 'Available'), ('offered', 'Offered'), ('requested', 'Requested'), ('awaiting', 'Awaiting Pickup'), ('completed', 'Completed')], default='', max_length=9)),
            ],
            options={
                'verbose_name_plural': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('other_category', models.CharField(blank=True, default='', max_length=128)),
                ('details', models.TextField(blank=True, default='')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('location_detail', models.CharField(blank=True, max_length=255, null=True)),
                ('image1', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image')),
                ('image2', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image')),
                ('image3', cloudinary.models.CloudinaryField(blank=True, default='', max_length=255, null=True, verbose_name='image')),
                ('location', models.CharField(choices=[('AUH', 'Abu Dhabi'), ('AJM', 'Ajman'), ('SHJ', 'Sharjah'), ('DXB', 'Dubai'), ('FUJ', 'Fujairah'), ('RAK', 'Ras Al Khaimah'), ('UAQ', 'Umm Al Quwain')], default='DXB', max_length=3)),
                ('post_type', models.CharField(choices=[('free', 'Free (I want to give something away)'), ('wanted', 'Wanted (I want to get something)')], default='free', max_length=6)),
                ('status', models.CharField(choices=[('available', 'Available'), ('completed', 'Completed'), ('awaiting', 'Awaiting Pickup'), ('onhold', 'On Hold'), ('removed', 'Removed')], default='available', max_length=10)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Category')),
                ('completed_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_completed_with', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-posted_on'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_message_check', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(choices=[('AUH', 'Abu Dhabi'), ('AJM', 'Ajman'), ('SHJ', 'Sharjah'), ('DXB', 'Dubai'), ('FUJ', 'Fujairah'), ('RAK', 'Ras Al Khaimah'), ('UAQ', 'Umm Al Quwain')], default='DXB', max_length=3)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('pickup_time', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('tag', models.CharField(blank=True, choices=[('request', 'Request'), ('offer', 'Offer'), ('question', 'Question'), ('report', 'Report'), ('reply', 'Reply')], default='request', max_length=9)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usermessages', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='items.Item')),
                ('related_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.UserMessage')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='items.Item'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
