# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 22:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20170613_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
